<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SonicDesktopRelay.Core\SonicDesktopRelay.Core.csproj" />
    <ProjectReference Include="..\SonicDesktopRelay.Media\SonicDesktopRelay.Media.csproj" />
    <ProjectReference Include="..\SonicDesktopRelay.Signaling\SonicDesktopRelay.Signaling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="10.0.16" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
